/* Living Conditions scene grammar, applied to the geographic Hormuz enclosure. */
window.createHormuz3D=(fallback,onSelect)=>{
  if(!window.THREE||!THREE.OrbitControls)return null;
  const T=THREE,dark=()=>document.documentElement.dataset.theme!=='light',Y=9,S=24;
  const position=(lon,lat,y=Y+.6)=>new T.Vector3((lon-50.5)*Math.cos(20*Math.PI/180)*S,y,-(lat-20)*S);
  const scene=new T.Scene();scene.background=new T.Color('#06131a');
  const camera=new T.PerspectiveCamera(34,1,.1,1800);camera.position.set(440,460,680);
  const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.outputEncoding=T.sRGBEncoding;
  const controls=new T.OrbitControls(camera,renderer.domElement);controls.target.set(0,Y,0);controls.enableDamping=true;controls.dampingFactor=.06;controls.enablePan=true;controls.minDistance=80;controls.maxDistance=1500;controls.minPolarAngle=.52;controls.maxPolarAngle=1.22;controls.update();const az=controls.getAzimuthalAngle();controls.minAzimuthAngle=az-Math.PI/2;controls.maxAzimuthAngle=az+Math.PI/2;
  scene.add(new T.HemisphereLight('#c5ddd9','#0b1518',1.25));const sun=new T.DirectionalLight('#ffe0a1',1.35);sun.position.set(-90,180,80);scene.add(sun);
  // Same thin gold IVM and solid pre-dawn field as Living Conditions.
  const vertices=[],spacing=34,h=spacing*Math.sqrt(3)/2,tetra=spacing*Math.sqrt(2/3);
  const point=(i,j,k)=>[i*spacing+j*spacing/2+k*spacing/2,-120+k*tetra,j*h+k*h/3];
  for(let k=0;k<=4;k++)for(let i=-9;i<=9;i++)for(let j=-9;j<=9;j++){const p=point(i,j,k);if(i<9)vertices.push(...p,...point(i+1,j,k));if(j<9)vertices.push(...p,...point(i,j+1,k));if(k<4)vertices.push(...p,...point(i,j,k+1));}
  function segments(points,color,opacity=1){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(points,3));return new T.LineSegments(g,new T.LineBasicMaterial({color,transparent:opacity<1,opacity,depthWrite:false}));}
  scene.add(segments(vertices,'#c9a34b',.16));const horizon=[];for(const angle of [0,Math.PI/3,-Math.PI/3]){const dx=Math.cos(angle),dz=Math.sin(angle);for(let o=-24;o<=24;o++){const cx=-dz*o*spacing,cz=dx*o*spacing;horizon.push(cx-dx*820,-4,cz-dz*820,cx+dx*820,-4,cz+dz*820);}}scene.add(segments(horizon,'#e1bb5b',.16));
  let seed=14031945;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296),stars=[];for(let i=0;i<1050;i++){const a=random()*Math.PI*2,e=-.28+Math.pow(random(),1.25)*1.15,r=720+random()*120;stars.push(Math.cos(a)*Math.cos(e)*r,Math.sin(e)*r-60,Math.sin(a)*Math.cos(e)*r);}const sg=new T.BufferGeometry();sg.setAttribute('position',new T.Float32BufferAttribute(stars,3));scene.add(new T.Points(sg,new T.PointsMaterial({color:'#e4edf5',size:1.8,transparent:true,opacity:.78,depthWrite:false})));
  const sea=new T.Mesh(new T.PlaneGeometry(21*Math.cos(20*Math.PI/180)*S,20*S),new T.MeshPhongMaterial({color:'#2c697b',side:T.DoubleSide,shininess:25,transparent:true,opacity:.24,depthWrite:false}));sea.rotation.x=-Math.PI/2;sea.position.y=Y;sea.renderOrder=1;scene.add(sea);
  let seabed=null;
  const coast=new T.Group(),vessels=new T.Group(),trail=new T.Group(),gate=new T.Group();scene.add(coast,vessels,trail,gate);
  for(const [name,lon,lat] of [['IRAN',58,28.5],['OMAN',57.6,23.2],['UAE',54.8,24.3],['PERSIAN GULF',53.5,27.2],['GULF OF OMAN',58.2,25.6],['YEMEN',47.5,15.5],['BAB EL-MANDEB',43.4,12.6],['RED SEA',41.8,17],['GULF OF ADEN',48,12],['DJIBOUTI',42.5,11.6]]){const c=document.createElement('canvas');c.width=512;c.height=64;const x=c.getContext('2d');x.font='bold 30px system-ui';x.textAlign='center';x.fillStyle='#f0e4c4';x.strokeStyle='#102027';x.lineWidth=4;x.strokeText(name,256,42);x.fillText(name,256,42);const texture=new T.CanvasTexture(c),sprite=new T.Sprite(new T.SpriteMaterial({map:texture,depthTest:false}));sprite.position.copy(position(lon,lat,Y+2));sprite.scale.set(35,4.4,1);scene.add(sprite);}
  let oldLand,oldGeo,lastShips,lastTrack,lastSelected,shipMeshes=[],theme='';
  let dem=null,terrainEnabled=true;
  const terrainLabel=document.createElement('label'),terrainToggle=document.createElement('input');terrainToggle.type='checkbox';terrainToggle.checked=true;terrainLabel.append(terrainToggle,document.createTextNode(' Land + seabed relief · 20× vertical'));document.querySelector('.hormuz-controls').append(terrainLabel);
  const key=document.querySelector('.hormuz-key');key.textContent='Ship blocks: reported flag state · stacked height separates overlapping markers, not actual altitude · water surface marks sea level';
  const legend=document.createElement('div');legend.className='ship-nationality-legend';legend.style.cssText='display:flex;flex-wrap:wrap;gap:8px 16px;padding:12px 18px;color:#e8e5da;font-size:12px';key.after(legend);
  const flag=s=>/^[A-Z]{2}$/.test(String(s.flag||'').toUpperCase())?String(s.flag).toUpperCase():'Unknown';
  const flagColor=f=>{if(f==='Unknown')return '#b7bcc2';const n=(f.charCodeAt(0)-65)*26+f.charCodeAt(1)-65;return new T.Color().setHSL((n*.61803398875)%1,.67,.58).getStyle();};
  let countryNames;try{countryNames=new Intl.DisplayNames(['en'],{type:'region'});}catch{}
  function renderLegend(ships){legend.replaceChildren();const counts=new Map();ships.forEach(s=>counts.set(flag(s),(counts.get(flag(s))||0)+1));for(const [f,n] of [...counts].sort((a,b)=>b[1]-a[1])){const item=document.createElement('span'),swatch=document.createElement('i');swatch.style.cssText=`display:inline-block;width:12px;height:12px;margin-right:6px;background:${flagColor(f)};border:1px solid #fff5`;item.append(swatch,document.createTextNode(`${f==='Unknown'?'Unknown flag':countryNames?.of(f)||f} · ${n}`));legend.append(item);}}
  const terrainStatus=document.createElement('p');terrainStatus.textContent='Loading regional terrain…';document.querySelector('.hormuz-key').after(terrainStatus);
  const credit=document.createElement('p'),creditLink=document.createElement('a');credit.textContent='Terrain: Mapzen on AWS · SRTM / GMTED2010 courtesy of USGS · ETOPO1 courtesy of NOAA. ';creditLink.href='https://github.com/tilezen/joerd/blob/master/docs/attribution.md';creditLink.textContent='Provider attribution';credit.append(creditLink);terrainStatus.after(credit);
  function heightAt(x,z){const lon=50.5+x/(S*Math.cos(20*Math.PI/180)),lat=20-z/S,gx=Math.max(0,Math.min(dem.width-1,(lon-40)/21*(dem.width-1))),gy=Math.max(0,Math.min(dem.height-1,(30-lat)/20*(dem.height-1))),i=Math.min(dem.width-2,Math.floor(gx)),j=Math.min(dem.height-2,Math.floor(gy)),a=gx-i,b=gy-j,v=(u,v)=>dem.metres[v*dem.width+u];return ((1-a)*(1-b)*v(i,j)+a*(1-b)*v(i+1,j)+(1-a)*b*v(i,j+1)+a*b*v(i+1,j+1))/111000*S*20;}
  function relief(g){const source=g.index?g.toNonIndexed():g,p=source.attributes.position,points=[];function triangle(a,b,c,depth=0){if(depth<10&&Math.max(a.distanceTo(b),b.distanceTo(c),c.distanceTo(a))>3){const ab=a.clone().add(b).multiplyScalar(.5),bc=b.clone().add(c).multiplyScalar(.5),ca=c.clone().add(a).multiplyScalar(.5);triangle(a,ab,ca,depth+1);triangle(ab,b,bc,depth+1);triangle(ca,bc,c,depth+1);triangle(ab,bc,ca,depth+1);}else for(const v of [a,b,c])points.push(v.x,heightAt(v.x,v.z),v.z);}
    for(let i=0;i<p.count;i+=3)triangle(new T.Vector3().fromBufferAttribute(p,i),new T.Vector3().fromBufferAttribute(p,i+1),new T.Vector3().fromBufferAttribute(p,i+2));if(source!==g)source.dispose();for(let i=1;i<points.length;i+=3)points[i]=Math.max(0,points[i]);const out=new T.BufferGeometry();out.setAttribute('position',new T.Float32BufferAttribute(points,3));out.computeVertexNormals();return out;}
  function applyTerrain(){if(!dem)return;coast.children.forEach(mesh=>{if(!mesh.isMesh)return;if(!mesh.userData.flat){mesh.userData.flat=mesh.geometry;mesh.userData.relief=relief(mesh.geometry);}mesh.geometry=terrainEnabled?mesh.userData.relief:mesh.userData.flat;});if(!seabed){const g=new T.PlaneGeometry(21*Math.cos(20*Math.PI/180)*S,20*S,dem.width-1,dem.height-1);g.rotateX(-Math.PI/2);const p=g.attributes.position,colors=[];for(let i=0;i<p.count;i++){const height=Math.min(0,heightAt(p.getX(i),p.getZ(i)));p.setY(i,height);const c=new T.Color('#5b9fa6').lerp(new T.Color('#112e48'),Math.min(1,-height/(3500/111000*S*20)));colors.push(c.r,c.g,c.b);}g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.computeVertexNormals();seabed=new T.Mesh(g,new T.MeshPhongMaterial({vertexColors:true,side:T.DoubleSide,shininess:5}));seabed.position.y=Y-.04;scene.add(seabed);}seabed.visible=terrainEnabled;terrainStatus.textContent=terrainEnabled?'Sourced land and seabed relief · 0.05° grid · 20× vertical exaggeration · translucent water at sea level':'Flat geographic reference · land and seabed relief off';}
  terrainToggle.onchange=()=>{terrainEnabled=terrainToggle.checked;applyTerrain();};
  fetch('assets/hormuz-terrain.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{dem=d;applyTerrain();}).catch(()=>{terrainStatus.textContent='Terrain unavailable; flat reference retained.';terrainToggle.checked=false;terrainToggle.disabled=true;});
  const clear=g=>{for(const o of [...g.children]){o.geometry?.dispose();o.material?.dispose();g.remove(o);}};
  const shape=rings=>{const sh=new T.Shape();rings.forEach((ring,i)=>{const p=i?new T.Path():sh;ring.forEach(([lon,lat],j)=>{const v=position(lon,lat);j?p.lineTo(v.x,-v.z):p.moveTo(v.x,-v.z);});p.closePath();if(i)sh.holes.push(p);});return sh;};
  function update({land,geo,ships,selected,track}){
    if(land&&land!==oldLand){clear(coast);for(const f of land.features)for(const rings of f.geometry.coordinates){const g=new T.ShapeGeometry(shape(rings));g.rotateX(-Math.PI/2);const mesh=new T.Mesh(g,new T.MeshPhongMaterial({color:'#6d7442',side:T.DoubleSide,shininess:7}));mesh.position.y=Y;coast.add(mesh);const edge=new T.LineSegments(new T.EdgesGeometry(g,8),new T.LineBasicMaterial({color:'#aaa071',transparent:true,opacity:.6}));edge.position.y=Y+.12;coast.add(edge);}oldLand=land;}
    if(geo&&geo!==oldGeo){clear(gate);for(const f of geo.features)if(f.properties.kind==='gate'){const points=[];const c=f.geometry.coordinates;for(let i=1;i<c.length;i++)points.push(...position(...c[i-1],Y+.3).toArray(),...position(...c[i],Y+.3).toArray());gate.add(segments(points,'#ffffff',.85));}oldGeo=geo;}
    if(ships!==lastShips||selected?.id!==lastSelected){clear(vessels);shipMeshes=[];const placed=[];for(const s of [...ships].sort((a,b)=>String(a.id).localeCompare(String(b.id)))){const p=position(s.lon,s.lat,Y),overlap=placed.filter(v=>Math.abs(v.x-p.x)<1.6&&Math.abs(v.z-p.z)<1.6),level=overlap.length?1+Math.max(...overlap.map(v=>v.level)):0;placed.push({x:p.x,z:p.z,level});const mesh=new T.Mesh(new T.BoxGeometry(1.6,.8,1.6),new T.MeshPhongMaterial({color:flagColor(flag(s)),shininess:18,emissive:s.id===selected?.id?'#514527':'#000000'}));mesh.position.set(p.x,Y+.4+level*.9,p.z);mesh.userData.ship=s;vessels.add(mesh);shipMeshes.push(mesh);const outline=new T.LineSegments(new T.EdgesGeometry(mesh.geometry),new T.LineBasicMaterial({color:s.id===selected?.id?'#ffffff':'#10252d',transparent:true,opacity:.8}));outline.position.copy(mesh.position);vessels.add(outline);}renderLegend(ships);lastShips=ships;lastSelected=selected?.id;}
    if(dem&&coast.children.some(mesh=>mesh.isMesh&&!mesh.userData.flat))applyTerrain();
    if(track!==lastTrack){clear(trail);const pts=[];for(let i=1;i<track.length;i++){const a=track[i-1],b=track[i];pts.push(...position(a.lon,a.lat,Y+.4).toArray(),...position(b.lon,b.lat,Y+.4).toArray());}trail.add(segments(pts,'#ffffff',.65));lastTrack=track;}
  }
  const ray=new T.Raycaster(),pointer=new T.Vector2();let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('click',e=>{if(down&&Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(shipMeshes)[0];if(hit)onSelect(hit.object.userData.ship);});
  fallback.hidden=true;fallback.style.display='none';fallback.parentElement.insertBefore(renderer.domElement,fallback);renderer.domElement.setAttribute('aria-label','3D Hormuz map. Drag to rotate, scroll to zoom; select vessels using the adjacent list.');renderer.domElement.setAttribute('role','img');
  const resize=()=>{const w=fallback.parentElement.clientWidth,h=innerWidth<750?440:650;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();};new ResizeObserver(resize).observe(fallback.parentElement);resize();
  let last=0;function frame(t){requestAnimationFrame(frame);if(document.hidden||t-last<1000/30)return;last=t;const current=dark()?'dark':'light';if(current!==theme){theme=current;scene.background.set(dark()?'#06131a':'#9db0ad');sea.material.color.set(dark()?'#181d16':'#858a6b');coast.children.forEach(o=>{if(o.isMesh)o.material.color.set(dark()?'#6d7442':'#b9ad7d');});}controls.update();renderer.render(scene,camera);}requestAnimationFrame(frame);
  const reset=document.createElement('button');reset.type='button';reset.textContent='Reset 3D view';reset.onclick=()=>{camera.position.set(440,460,680);controls.target.set(0,Y,0);controls.update();};document.querySelector('.hormuz-controls').append(reset);
  for(const [name,lon,lat] of [['Focus Hormuz',56.5,26],['Focus Yemen / Bab el-Mandeb',44.5,13.5]]){const button=document.createElement('button');button.type='button';button.textContent=name;button.onclick=()=>{const target=position(lon,lat,Y);controls.target.copy(target);camera.position.copy(target).add(new T.Vector3(110,135,190));controls.update();};document.querySelector('.hormuz-controls').append(button);}
  return {update};
};
