(()=>{
  'use strict';
  const start=()=>{
    const data=window.WAR_MAPS_DATA,model=window.WAR_MAPS_NETWORK_MODEL,root=document.querySelector('#navigator');
    if(!data||!model||!root)return;
    const $=selector=>document.querySelector(selector),esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
    if(!window.ForceGraph3D){root.innerHTML='<p class="navigator-loading">The 3D renderer is unavailable. <a href="graph.html">Open the accessible Network Graph</a>.</p>';return;}
    const params=new URLSearchParams(location.search),catalog=new Map(),edgeIndex=new Map(),adjacency=new Map(),nationNames=new Set();
    const kindLabel={nation:'Nation',conflict:'Conflict',event:'Event',human:'Human',organization:'Organization',location:'Place'};
    const kindColor={nation:'#7e914b',conflict:'#f07800',event:'#d8c58f',human:'#58a7b8',organization:'#b56d4d',location:'#8d79a8'};
    const kindSize={nation:7.5,conflict:11,event:2.6,human:5.5,organization:6.5,location:5};
    const addNode=(id,label,kind,metadata={})=>{if(!catalog.has(id))catalog.set(id,{id,label,kind,metadata});else Object.assign(catalog.get(id).metadata,metadata);return catalog.get(id);};
    const endpoint=value=>typeof value==='object'?value.id:value;
    const addEdge=(source,target,relation,metadata={})=>{
      if(!source||!target||source===target||!catalog.has(source)||!catalog.has(target))return;
      const key=`${[source,target].sort().join('\u0000')}\u0000${relation}`;
      if(edgeIndex.has(key)){Object.assign(edgeIndex.get(key).metadata,metadata);return;}
      const edge={source,target,relation,metadata};edgeIndex.set(key,edge);
      if(!adjacency.has(source))adjacency.set(source,new Map());if(!adjacency.has(target))adjacency.set(target,new Map());
      if(!adjacency.get(source).has(target))adjacency.get(source).set(target,[]);if(!adjacency.get(target).has(source))adjacency.get(target).set(source,[]);
      adjacency.get(source).get(target).push(edge);adjacency.get(target).get(source).push(edge);
    };
    const nationId=name=>{name=model.display(String(name||'').trim());return nationNames.has(name)?`nation:${name}`:'';};
    const personName=value=>{
      const raw=String(value||'').trim(),forced=raw.match(/^Forces of ([A-Z][\p{L}'’.-]+(?:\s+[A-Z][\p{L}'’.-]+){1,4})$/u),name=forced?.[1]||raw;
      if(/\b(government|army|forces|front|movement|party|militia|brigade|battalion|tribe|clan|police|council|state|islamic|liberation|insurgents?|faction|community|group)\b/i.test(name)||name.includes(',')||/^[A-Z\d/-]{2,12}$/.test(name))return '';
      return /^[A-Z][\p{L}'’.-]+(?:\s+(?:al-|bin |ibn )?[A-Z][\p{L}'’.-]+){1,4}$/u.test(name)?name:'';
    };
    const actorNode=value=>{
      const label=String(value||'').trim();if(!label)return '';
      const regime=model.regimeCountry(label,nationNames);if(regime)return nationId(regime);
      const person=personName(label);if(person){const id=`human:${person}`;addNode(id,person,'human',{sourceLabel:label});return id;}
      const id=`organization:actor:${label}`;addNode(id,label,'organization',{actor:true});return id;
    };
    (data.nations||[]).forEach(profile=>nationNames.add(model.display(profile.country)));
    (data.nations||[]).forEach(profile=>{const name=model.display(profile.country);addNode(`nation:${name}`,name,'nation',{profile});});
    const organizationsByNation=new Map();
    (data.organizations||[]).forEach(organization=>{
      const id=`organization:${organization.id}`;addNode(id,organization.name,'organization',{organization});
      (organization.members||organization.entity_nations||[]).forEach(member=>{const nation=nationId(member);if(!nation)return;addEdge(id,nation,'member state',{source:organization.source_id});if(!organizationsByNation.has(nation))organizationsByNation.set(nation,new Set());organizationsByNation.get(nation).add(id);});
    });
    (data.conflicts||[]).forEach(conflict=>addNode(`conflict:${conflict.id}`,conflict.title,'conflict',{conflict}));
    (data.nations||[]).forEach(profile=>(profile.conflict_ids||[]).forEach(conflictId=>addEdge(`nation:${model.display(profile.country)}`,`conflict:${conflictId}`,'recorded participant')));
    (data.conflict_years||[]).forEach(row=>{
      const conflict=`conflict:${row.conflict_id}`;if(!catalog.has(conflict))return;
      (row.side_a_states||[]).forEach(name=>{const id=nationId(name);if(id)addEdge(conflict,id,'Side A participant',{side:'A',year:row.year});});
      (row.side_b_states||[]).forEach(name=>{const id=nationId(name);if(id)addEdge(conflict,id,'Side B participant',{side:'B',year:row.year});});
      model.split(row.side_a).forEach(name=>{const id=actorNode(name);if(id)addEdge(conflict,id,'Side A actor',{side:'A',year:row.year});});
      model.split(row.side_b).forEach(name=>{const id=actorNode(name);if(id)addEdge(conflict,id,'Side B actor',{side:'B',year:row.year});});
    });
    (data.events||[]).forEach(event=>{
      const id=`event:${event.id}`,label=`${event.date_start} · ${event.place||event.country||event.conflict_name||'recorded event'}`;
      addNode(id,label,'event',{event,date:event.date_start});addEdge(id,`conflict:${event.conflict_id}`,'event in conflict',{date:event.date_start});
      const place=model.display(event.network_location||event.place||event.country||'Unspecified location'),placeId=`location:${place}`;addNode(placeId,place,'location',{place});addEdge(id,placeId,'occurred at',{date:event.date_start});
      const territory=nationId(event.country);if(territory)addEdge(id,territory,'occurred in territory',{date:event.date_start});
      (event.side_a_states||[]).forEach(name=>{const nation=nationId(name);if(nation)addEdge(id,nation,'Side A event participant',{side:'A',date:event.date_start});});
      (event.side_b_states||[]).forEach(name=>{const nation=nationId(name);if(nation)addEdge(id,nation,'Side B event participant',{side:'B',date:event.date_start});});
      const observationNations=new Set([territory,...(event.side_a_states||[]).map(nationId),...(event.side_b_states||[]).map(nationId)].filter(Boolean));observationNations.forEach(nation=>(organizationsByNation.get(nation)||[]).forEach(organization=>addEdge(id,organization,'observation involving member state',{viaNation:nation,date:event.date_start,coordinationInferred:false})));
      model.split(event.side_a).forEach(name=>{const actor=actorNode(name);if(actor)addEdge(id,actor,'Side A event actor',{side:'A',date:event.date_start});});
      model.split(event.side_b).forEach(name=>{const actor=actorNode(name);if(actor)addEdge(id,actor,'Side B event actor',{side:'B',date:event.date_start});});
      if(event.alleged_perpetrator){const actor=actorNode(event.alleged_perpetrator);if(actor)addEdge(id,actor,'reported attribution',{confidence:event.attribution_confidence,date:event.date_start});}
    });
    const graphSource=params.get('source')==='graph';
    if(graphSource){
      const throughYear=Number(params.get('through')||2025),minYears=Number(params.get('minYears')||1),relationship=params.get('relationship')||'observed',organizationIds=(params.get('organizations')||'').split(',').filter(Boolean),selectedOrganizations=(data.organizations||[]).filter(item=>organizationIds.includes(item.id)),includeUngrouped=params.get('includeUngrouped')==='1',selectedMembers=new Set(selectedOrganizations.flatMap(item=>item.members||item.entity_nations||[]).map(name=>model.display(name))),includeNation=name=>!selectedOrganizations.length||includeUngrouped||selectedMembers.has(model.display(name));
      edgeIndex.clear();adjacency.clear();
      [...catalog.keys()].forEach(id=>{const node=catalog.get(id);if(node?.kind==='nation'&&!includeNation(node.label))catalog.delete(id);if(node?.kind==='organization'&&(!selectedOrganizations.some(item=>`organization:${item.id}`===id)||relationship==='observed'))catalog.delete(id);if(node?.kind!=='nation'&&node?.kind!=='organization')catalog.delete(id);});
      (data.nations||[]).forEach(profile=>{if(!includeNation(profile.country)||relationship==='organization')return;const source=nationId(profile.country);(profile.same_side_partners||[]).forEach(relation=>{const target=nationId(relation.country),lastYear=Math.min(Number(relation.last_year||throughYear),throughYear),years=Math.max(0,lastYear-Number(relation.first_year||lastYear)+1);if(source&&target&&source!==target&&years>=minYears&&Number(relation.first_year||0)<=throughYear)addEdge(source,target,'shared-side participation',{years,firstYear:relation.first_year,lastYear});});});
      if(selectedOrganizations.length&&relationship!=='observed'){selectedOrganizations.forEach(organization=>{const organizationId=`organization:${organization.id}`;if(!catalog.has(organizationId))return;(organization.members||organization.entity_nations||[]).forEach(member=>{const nation=nationId(member);if(nation)addEdge(organizationId,nation,'member state',{source:organization.source_id});});});}
    }
    const topologyNames={equilibrium:'Equilibrium sphere',coalitions:'Connection shells',barabasi:'Barabási hub field','erdos-renyi':'Erdős–Rényi distribution','watts-strogatz':'Watts–Strogatz ring',radial:'Degree radial',lattice:'Cubic lattice',prisoner:'Opposing fields','third-party':'Bridge landscape',pirates:'Influence hierarchy',temporal:'Temporal landscape'};
    const requestedTopology=params.get('topology'),state={center:'',root:'',history:[],visibleIds:new Set(),batchOffsets:new Map(),nodes:[],links:[],graph:null,positions:new Map(),layoutForce:null,collisionForce:null,magneticForce:null,type:'all',topology:topologyNames[requestedTopology]?requestedTopology:'equilibrium',idleTimer:null};
    const globalDegree=id=>adjacency.get(id)?.size||0;
    const relationToCenter=id=>(adjacency.get(state.center)?.get(id)||[])[0]||null;
    const seeded=value=>{let seed=0;for(const char of String(value))seed=(seed*31+char.charCodeAt(0))>>>0;return ()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};};
    function localPositions(){
      const positions=new Map([[state.center,{x:0,y:0,z:0}]]),neighbors=state.nodes.filter(node=>node.id!==state.center).sort((a,b)=>a.kind.localeCompare(b.kind)||a.label.localeCompare(b.label)),count=Math.max(1,neighbors.length),random=seeded(`${state.center}|${state.topology}`),sphere=(index,total,radius,center={x:0,y:0,z:0},phase=0)=>model.spherePoint(index,total,radius,center,phase);
      if(state.topology==='coalitions'){
        const groups=[...new Set(neighbors.map(node=>node.kind))];groups.forEach((kind,groupIndex)=>{const members=neighbors.filter(node=>node.kind===kind),angle=groupIndex/Math.max(1,groups.length)*Math.PI*2,center={x:Math.cos(angle)*205,y:Math.sin(angle)*90,z:Math.sin(angle)*205};members.forEach((node,index)=>positions.set(node.id,sphere(index,members.length,Math.min(105,34+Math.sqrt(members.length)*8),center,groupIndex)));});
      }else if(state.topology==='barabasi'){
        const ranked=[...neighbors].sort((a,b)=>globalDegree(b.id)-globalDegree(a.id)||a.label.localeCompare(b.label));ranked.forEach((node,index)=>{const radius=58+Math.sqrt(index+1)*34,angle=index*2.399963;positions.set(node.id,{x:Math.cos(angle)*radius,y:Math.log2(1+globalDegree(node.id))*24-95,z:Math.sin(angle)*radius});});
      }else if(state.topology==='erdos-renyi'){
        neighbors.forEach(node=>positions.set(node.id,{x:(random()-.5)*430,y:(random()-.5)*330,z:(random()-.5)*430}));
      }else if(state.topology==='watts-strogatz'){
        neighbors.forEach((node,index)=>{const angle=index/count*Math.PI*2,radius=190+(index%3-1)*18;positions.set(node.id,{x:Math.cos(angle)*radius,y:(index%5-2)*26,z:Math.sin(angle)*radius});});
      }else if(state.topology==='radial'){
        const depths=globalDistances(state.center,3);neighbors.forEach((node,index)=>{const depth=depths.get(node.id)||3,members=neighbors.filter(item=>(depths.get(item.id)||3)===depth),slot=members.findIndex(item=>item.id===node.id),angle=slot/Math.max(1,members.length)*Math.PI*2,radius=depth*105;positions.set(node.id,{x:Math.cos(angle)*radius,y:(slot%3-1)*24,z:Math.sin(angle)*radius});});
      }else if(state.topology==='lattice'){
        const side=Math.ceil(Math.cbrt(count));neighbors.forEach((node,index)=>{const x=index%side,y=Math.floor(index/side)%side,z=Math.floor(index/(side*side));positions.set(node.id,{x:(x-(side-1)/2)*82,y:(y-(side-1)/2)*82,z:(z-(side-1)/2)*82});});
      }else if(state.topology==='prisoner'){
        const sides={A:[],B:[],other:[]};neighbors.forEach(node=>{const side=relationToCenter(node.id)?.metadata?.side;sides[side==='A'?'A':side==='B'?'B':'other'].push(node);});
        sides.A.forEach((node,index)=>positions.set(node.id,sphere(index,sides.A.length,130,{x:-190,y:0,z:-70},.4)));sides.B.forEach((node,index)=>positions.set(node.id,sphere(index,sides.B.length,130,{x:190,y:0,z:70},Math.PI+.4)));sides.other.forEach((node,index)=>positions.set(node.id,sphere(index,sides.other.length,165,{x:0,y:145,z:0},1.2)));
      }else if(state.topology==='third-party'){
        const ranked=[...neighbors].sort((a,b)=>globalDegree(b.id)-globalDegree(a.id)||a.label.localeCompare(b.label));ranked.forEach((node,index)=>{const reach=globalDegree(node.id),radius=70+Math.min(260,index*3.2),angle=index*2.399963;positions.set(node.id,{x:Math.cos(angle)*radius,y:Math.log2(1+reach)*22-90,z:Math.sin(angle)*radius});});
      }else if(state.topology==='pirates'){
        const ranked=[...neighbors].sort((a,b)=>globalDegree(b.id)-globalDegree(a.id)||a.label.localeCompare(b.label));ranked.forEach((node,index)=>{const level=Math.floor(Math.sqrt(index)),angle=index*2.399963,radius=58+level*29;positions.set(node.id,{x:Math.cos(angle)*radius,y:190-level*42,z:Math.sin(angle)*radius});});
      }else if(state.topology==='temporal'){
        const dated=neighbors.filter(node=>node.metadata.date||node.metadata.event?.date_start),undated=neighbors.filter(node=>!dated.includes(node)),times=dated.map(node=>Date.parse(`${node.metadata.date||node.metadata.event.date_start}T00:00:00Z`)).filter(Number.isFinite),min=Math.min(...times),max=Math.max(...times),span=Math.max(1,max-min);
        dated.forEach((node,index)=>{const time=Date.parse(`${node.metadata.date||node.metadata.event.date_start}T00:00:00Z`),turn=index*2.399963,radius=115+index%5*9;positions.set(node.id,{x:Math.cos(turn)*radius,y:-190+(time-min)/span*380,z:Math.sin(turn)*radius});});undated.forEach((node,index)=>positions.set(node.id,sphere(index,undated.length,225,{x:0,y:0,z:0},.8)));
      }else neighbors.forEach((node,index)=>positions.set(node.id,sphere(index,count,120+Math.min(210,Math.sqrt(count)*15),{x:0,y:0,z:0},random()*Math.PI*2)));
      return positions;
    }
    const kindOrder={nation:0,organization:1,human:2,location:3,conflict:4,event:5};
    function orderedNeighbors(id){return [...(adjacency.get(id)?.keys()||[])].sort((left,right)=>{const a=catalog.get(left),b=catalog.get(right);return (kindOrder[a?.kind]??9)-(kindOrder[b?.kind]??9)||globalDegree(right)-globalDegree(left)||(a?.label||'').localeCompare(b?.label||'');});}
    function globalDistances(id,maxDepth=3){const distances=new Map([[id,0]]),queue=[id];while(queue.length){const current=queue.shift(),depth=distances.get(current);if(depth>=maxDepth)continue;(adjacency.get(current)?.keys()||[]).forEach(next=>{if(distances.has(next))return;distances.set(next,depth+1);queue.push(next);});}return distances;}
    function expandTen(id){const ordered=orderedNeighbors(id),offset=state.batchOffsets.get(id)||0,batch=ordered.slice(offset,offset+10);state.batchOffsets.set(id,Math.min(ordered.length,offset+10));state.visibleIds.add(id);batch.forEach(nodeId=>state.visibleIds.add(nodeId));return batch.length;}
    function pruneDistant(){const distances=globalDistances(state.center,3);state.visibleIds.forEach(id=>{if(!distances.has(id))state.visibleIds.delete(id);});state.visibleIds.add(state.center);}
    function visibleGraph(){const nodes=[...state.visibleIds].map(nodeId=>catalog.get(nodeId)).filter(Boolean).map(node=>({...node,metadata:node.metadata})),links=[...edgeIndex.values()].filter(edge=>state.visibleIds.has(endpoint(edge.source))&&state.visibleIds.has(endpoint(edge.target))).map(edge=>({...edge,source:endpoint(edge.source),target:endpoint(edge.target),metadata:edge.metadata}));return {nodes,links};}
    function analyzeVisible(){
      const ids=state.nodes.map(node=>node.id),local=new Map(ids.map(id=>[id,new Set()]));state.links.forEach(link=>{const a=endpoint(link.source),b=endpoint(link.target);local.get(a)?.add(b);local.get(b)?.add(a);});const between=new Map(ids.map(id=>[id,0]));
      ids.forEach(source=>{const stack=[],predecessors=new Map(ids.map(id=>[id,[]])),sigma=new Map(ids.map(id=>[id,0])),distance=new Map(ids.map(id=>[id,-1])),queue=[source];sigma.set(source,1);distance.set(source,0);while(queue.length){const vertex=queue.shift();stack.push(vertex);local.get(vertex)?.forEach(next=>{if(distance.get(next)<0){queue.push(next);distance.set(next,distance.get(vertex)+1);}if(distance.get(next)===distance.get(vertex)+1){sigma.set(next,sigma.get(next)+sigma.get(vertex));predecessors.get(next).push(vertex);}});}const dependency=new Map(ids.map(id=>[id,0]));while(stack.length){const target=stack.pop();predecessors.get(target).forEach(previous=>dependency.set(previous,dependency.get(previous)+(sigma.get(previous)/Math.max(1,sigma.get(target)))*(1+dependency.get(target))));if(target!==source)between.set(target,between.get(target)+dependency.get(target));}});
      const normalizer=Math.max(1,(ids.length-1)*(ids.length-2));state.nodes.forEach(node=>{const degree=local.get(node.id)?.size||0,degreeShare=degree/Math.max(1,ids.length-1),betweenness=between.get(node.id)/normalizer;node.networkMetrics={degree,degreeShare,betweenness,magnetism:.2+degreeShare*1.8+betweenness*4};});
    }
    function magneticForce(){let nodes=[];const force=alpha=>{const byId=new Map(nodes.map(node=>[node.id,node]));state.links.forEach(link=>{const a=byId.get(endpoint(link.source)),b=byId.get(endpoint(link.target));if(!a||!b)return;const dx=(b.x||0)-(a.x||0),dy=(b.y||0)-(a.y||0),dz=(b.z||0)-(a.z||0),distance=Math.max(1,Math.hypot(dx,dy,dz)),pull=.0045*alpha/distance,am=a.networkMetrics?.magnetism||.2,bm=b.networkMetrics?.magnetism||.2;a.vx=(a.vx||0)+dx*pull*bm;a.vy=(a.vy||0)+dy*pull*bm;a.vz=(a.vz||0)+dz*pull*bm;b.vx=(b.vx||0)-dx*pull*am;b.vy=(b.vy||0)-dy*pull*am;b.vz=(b.vz||0)-dz*pull*am;});};force.initialize=value=>{nodes=value||[];};return force;}
    const nodeValue=node=>(kindSize[node.kind]||4)+Math.sqrt(node.networkMetrics?.degree||0)*1.8+Math.sqrt(node.networkMetrics?.betweenness||0)*22;
    function updateInspector(){
      const center=catalog.get(state.center),allNeighbors=adjacency.get(state.center)||new Map(),loaded=[...allNeighbors.keys()].filter(id=>state.visibleIds.has(id)),counts={};loaded.forEach(id=>{const kind=catalog.get(id)?.kind||'other';counts[kind]=(counts[kind]||0)+1;});
      $('#navigator-kind').textContent=kindLabel[center.kind]||center.kind;$('#navigator-selected').textContent=center.label;
      let detail='';if(center.kind==='nation')detail=`${center.metadata.profile?.conflict_count||0} recorded conflicts`;else if(center.kind==='conflict')detail=`${center.metadata.conflict?.first_active_year||''}–${center.metadata.conflict?.active_at_source_boundary?'present':center.metadata.conflict?.last_active_year||''}`;else if(center.kind==='event'){const event=center.metadata.event;detail=`${event.date_start} · ${event.fatalities?.best||0} best-estimate fatalities`;}else if(center.kind==='organization')detail=center.metadata.organization?.note||'Recorded organization or conflict actor';else if(center.kind==='human')detail='Named human reference in a source record';else detail='Recorded place connection';
      const metrics=state.nodes.find(node=>node.id===state.center)?.networkMetrics||{},remaining=Math.max(0,allNeighbors.size-(state.batchOffsets.get(state.center)||0));$('#navigator-inspector-content').innerHTML=`<p>${esc(detail)}</p><p><b>${loaded.length.toLocaleString()}</b> of <b>${allNeighbors.size.toLocaleString()}</b> direct connections loaded · <b>${state.links.length.toLocaleString()}</b> visible relations through three degrees.</p><p>Visible degree <b>${metrics.degree||0}</b> · degree share <b>${((metrics.degreeShare||0)*100).toFixed(1)}%</b> · normalized betweenness <b>${(metrics.betweenness||0).toFixed(3)}</b>.</p><div class="navigator-kind-grid">${Object.entries(counts).sort().map(([kind,total])=>`<span><i class="navigator-dot" style="--dot:${kindColor[kind]||'#888'}"></i><b>${total}</b> ${esc(kindLabel[kind]||kind)}</span>`).join('')}</div>${remaining?`<button id="navigator-more" type="button">Add next ${Math.min(10,remaining)} connections</button>`:''}<small>Node size follows betweenness and degree. Degree share and betweenness increase magnetic pull. Nodes retire only after they move beyond the third degree from the center.</small>`;$('#navigator-more')?.addEventListener('click',()=>focus(state.center));
    }
    function updateConnections(){
      const neighbors=adjacency.get(state.center)||new Map(),rows=[...neighbors].filter(([id])=>state.visibleIds.has(id)).map(([id,edges])=>({node:catalog.get(id),edges})).filter(row=>row.node).sort((a,b)=>(kindOrder[a.node.kind]??9)-(kindOrder[b.node.kind]??9)||a.node.label.localeCompare(b.node.label));
      $('#navigator-date').textContent=`${rows.length.toLocaleString()} of ${neighbors.size.toLocaleString()} direct · ${topologyNames[state.topology]}`;
      $('#navigator-register-list').innerHTML=rows.map(({node,edges})=>`<button type="button" data-node="${esc(node.id)}"><small>${esc(kindLabel[node.kind]||node.kind)}</small><strong>${esc(node.label)}</strong><span>${esc([...new Set(edges.map(edge=>edge.relation))].join(' · '))}</span></button>`).join('')||'<p class="navigator-loading">No direct connections in the source index.</p>';
    }
    function nodeColor(node){if(node.id===state.center)return '#ffd500';if(state.type!=='all'&&node.kind!==state.type)return '#18201d';return kindColor[node.kind]||'#8a8a72';}
    function nodeLabel(node){const direct=[...new Set((adjacency.get(state.center)?.get(node.id)||[]).map(edge=>edge.relation))].join(' · '),depth=globalDistances(state.center,3).get(node.id),degree=depth===1?'First':depth===2?'Second':depth===3?'Third':'',metrics=node.networkMetrics||{};const relation=node.id===state.center?'Central node':direct||`${degree}-degree retained connection`;return `<div style="font-size:17px"><b>${esc(node.label)}</b></div><small style="font-size:13px;color:${kindColor[node.kind]||'#aaa'}">${esc(kindLabel[node.kind]||node.kind)} · ${esc(relation)}</small><br><small>degree ${metrics.degree||0} · betweenness ${(metrics.betweenness||0).toFixed(3)}</small>`;}
    function optimize(duration=900){state.positions=localPositions();state.nodes.forEach(node=>{const point=state.positions.get(node.id)||{x:0,y:0,z:0};node.fx=null;node.fy=null;node.fz=null;node.x=point.x;node.y=point.y;node.z=point.z;});state.layoutForce?.targets(state.positions);state.graph?.graphData({nodes:state.nodes,links:state.links}).refresh();setTimeout(()=>{state.graph?.d3ReheatSimulation();state.graph?.zoomToFit(duration,90);},50);}
    function pullNeighborhood(node,translation){const distance=Math.hypot(translation.x||0,translation.y||0,translation.z||0);if(!distance)return;model.graphDistances(node.id,state.links,3).forEach((depth,id)=>{const neighbor=state.nodes.find(item=>item.id===id),factor=model.dragPullFactor(depth,distance);if(!neighbor||!factor)return;const dx=(translation.x||0)*factor,dy=(translation.y||0)*factor,dz=(translation.z||0)*factor;neighbor.x=(neighbor.x||0)+dx;neighbor.y=(neighbor.y||0)+dy;neighbor.z=(neighbor.z||0)+dz;const target=state.positions.get(id);if(target){target.x+=dx;target.y+=dy;target.z+=dz;}});}
    function focus(id,{remember=true,expand=true}={}){
      if(!catalog.has(id))return;if(remember&&state.center&&state.center!==id)state.history.push(state.center);state.center=id;state.visibleIds.add(id);if(expand)expandTen(id);pruneDistant();const local=visibleGraph();state.nodes=local.nodes;state.links=local.links;analyzeVisible();state.positions=localPositions();state.nodes.forEach(node=>Object.assign(node,state.positions.get(node.id)||{}));
      if(!state.graph){renderGraph();return;}state.layoutForce=model.anchorForce(state.positions);state.collisionForce=model.collisionForce(node=>node.id===state.center?34:({nation:24,conflict:28,event:7,human:14,organization:17,location:15}[node.kind]||12),5);state.magneticForce=magneticForce();
      state.graph.graphData({nodes:state.nodes,links:state.links}).d3Force('layout',state.layoutForce).d3Force('collision',state.collisionForce).d3Force('magnetism',state.magneticForce).nodeColor(nodeColor).nodeVal(nodeValue).refresh();state.graph.d3Force('link')?.strength(link=>.04+Math.max(link.source.networkMetrics?.magnetism||.2,link.target.networkMetrics?.magnetism||.2)*.12);$('#navigator-title').textContent=centerTitle();$('#navigator-status').textContent=statusText();updateInspector();updateConnections();syncLabels();setTimeout(()=>{state.graph.d3ReheatSimulation();state.graph.zoomToFit(850,90);},30);
    }
    const centerTitle=()=>`${catalog.get(state.center)?.label||'Network'} · Network Browser`,statusText=()=>`${state.nodes.length.toLocaleString()} retained nodes · ${state.links.length.toLocaleString()} observed relations · click center again for 10 more`;
    function markInteraction(){if(!state.graph)return;state.graph.controls().autoRotate=false;clearTimeout(state.idleTimer);state.idleTimer=setTimeout(()=>{if(!state.graph)return;state.graph.controls().autoRotate=true;state.graph.resumeAnimation();},6000);}
    function syncLabels(){let layer=$('#navigator-node-labels');if(!layer){layer=document.createElement('div');layer.id='navigator-node-labels';layer.className='navigator-node-labels';document.body.append(layer);}const ranked=[...state.nodes].sort((a,b)=>nodeValue(b)-nodeValue(a)),shown=new Set([state.center,...ranked.slice(0,39).map(node=>node.id)]);layer.innerHTML=state.nodes.filter(node=>shown.has(node.id)).map(node=>`<span class="navigator-node-label ${node.id===state.center?'central':''}" data-label-node="${esc(node.id)}">${esc(node.label)}</span>`).join('');updateLabels();}
    function updateLabels(){if(!state.graph)return;document.querySelectorAll('[data-label-node]').forEach(label=>{const node=state.nodes.find(item=>item.id===label.dataset.labelNode);if(!node||!Number.isFinite(node.x)){label.hidden=true;return;}const point=state.graph.graph2ScreenCoords(node.x,node.y,node.z),filtered=state.type!=='all'&&node.kind!==state.type;label.hidden=filtered||point.x<0||point.y<0||point.x>innerWidth-290||point.y>innerHeight;label.style.left=`${point.x}px`;label.style.top=`${point.y}px`;});}
    function renderGraph(){
      root.innerHTML='';const graph=ForceGraph3D()(root).backgroundColor('rgba(0,0,0,0)').showNavInfo(false).nodeLabel(nodeLabel).nodeColor(nodeColor).nodeVal(nodeValue).nodeOpacity(.98).nodeResolution(12).linkColor(link=>{const source=endpoint(link.source),target=endpoint(link.target);return source===state.center||target===state.center?'#d6c67d':'#59645d';}).linkOpacity(.62).linkWidth(link=>endpoint(link.source)===state.center||endpoint(link.target)===state.center?1.4:.45).enableNodeDrag(true).enableNavigationControls(true).onNodeClick(node=>{markInteraction();focus(node.id);}).onNodeDrag((node,translation)=>pullNeighborhood(node,translation)).onNodeDragEnd(node=>{node.fx=null;node.fy=null;node.fz=null;state.positions.set(node.id,{x:node.x,y:node.y,z:node.z});state.layoutForce?.targets(state.positions);graph.d3ReheatSimulation();}).onEngineTick(updateLabels).graphData({nodes:state.nodes,links:state.links});
      state.graph=graph;state.layoutForce=model.anchorForce(state.positions);state.collisionForce=model.collisionForce(node=>node.id===state.center?34:({nation:24,conflict:28,event:7,human:14,organization:17,location:15}[node.kind]||12),5);state.magneticForce=magneticForce();graph.d3Force('layout',state.layoutForce);graph.d3Force('collision',state.collisionForce);graph.d3Force('magnetism',state.magneticForce);graph.d3Force('charge')?.strength(state.nodes.length>500?-32:-58);graph.d3Force('link')?.distance(link=>endpoint(link.source)===state.center||endpoint(link.target)===state.center?70:42).strength(link=>.04+Math.max(link.source.networkMetrics?.magnetism||.2,link.target.networkMetrics?.magnetism||.2)*.12);graph.controls().enableDamping=true;graph.controls().dampingFactor=.075;graph.controls().autoRotate=true;graph.controls().autoRotateSpeed=.22;['pointerdown','wheel','touchstart'].forEach(type=>root.addEventListener(type,markInteraction,{passive:true}));$('#navigator-title').textContent=centerTitle();$('#navigator-status').textContent=statusText();updateInspector();updateConnections();syncLabels();optimize(700);
    }
    const requestedNode=params.get('node'),requestedConflict=params.get('conflict')?`conflict:${params.get('conflict')}`:'',defaultConflict=catalog.has('conflict:ucdp-candidate-16905')?'conflict:ucdp-candidate-16905':`conflict:${data.conflicts.at(-1)?.id}`;
    state.root=catalog.has(requestedConflict)?requestedConflict:catalog.has(requestedNode)?requestedNode:defaultConflict;state.center=state.root;state.visibleIds.add(state.root);expandTen(state.root);const initial=visibleGraph();state.nodes=initial.nodes;state.links=initial.links;analyzeVisible();state.positions=localPositions();state.nodes.forEach(node=>Object.assign(node,state.positions.get(node.id)||{}));
    const resetToRoot=()=>{state.history=[];state.visibleIds=new Set([state.root]);state.batchOffsets=new Map();focus(state.root,{remember:false});};
    $('#navigator-topology').value=state.topology;$('#navigator-register-list').addEventListener('click',event=>{const button=event.target.closest('[data-node]');if(button){markInteraction();focus(button.dataset.node);}});$('#navigator-back').addEventListener('click',()=>{const id=state.history.pop();if(id)focus(id,{remember:false,expand:false});});$('#navigator-root').addEventListener('click',resetToRoot);$('#navigator-clear').addEventListener('click',resetToRoot);
    $('#navigator-fit').addEventListener('click',()=>state.graph?.zoomToFit(650,90));$('#navigator-optimize').addEventListener('click',()=>optimize());$('#navigator-topology').addEventListener('change',event=>{state.topology=event.target.value;optimize();updateConnections();});$('#navigator-type').addEventListener('change',event=>{state.type=event.target.value;state.graph?.nodeColor(nodeColor).refresh();updateLabels();});
    $('#navigator-search').addEventListener('keydown',event=>{if(event.key!=='Enter')return;const query=event.currentTarget.value.trim().toLowerCase();if(!query)return;const matches=[...catalog.values()].filter(node=>state.type==='all'||node.kind===state.type).sort((a,b)=>{const ax=a.label.toLowerCase()===query?0:a.label.toLowerCase().startsWith(query)?1:2,bx=b.label.toLowerCase()===query?0:b.label.toLowerCase().startsWith(query)?1:2;return ax-bx||globalDegree(b.id)-globalDegree(a.id);}),match=matches.find(node=>node.label.toLowerCase().includes(query));if(match)focus(match.id);});
    $('#navigator-close').addEventListener('click',()=>{if(history.length>1)history.back();else location.href='graph.html';});
    try{renderGraph();}catch(error){const fallback=new URL('graph.html',location.href),center=catalog.get(state.center);if(center?.kind==='nation')fallback.searchParams.set('node',center.label);root.innerHTML=`<p class="navigator-loading">The browser could not create a WebGL context. <a href="${fallback.href}">Continue through this node in the Network Graph</a>.</p>`;$('#navigator-title').textContent='3D Network Browser unavailable';$('#navigator-status').textContent=error.message;updateInspector();updateConnections();}
  };
  window.addEventListener('load',start,{once:true});
})();
