(()=>{
  const start=()=>{
    const data=window.WAR_MAPS_DATA,model=window.WAR_MAPS_NETWORK_MODEL,root=document.querySelector('#navigator');
    if(!data||!model||!window.ForceGraph3D)return;
    const params=new URLSearchParams(location.search),conflict=data.conflicts.find(item=>item.id===params.get('conflict'))||data.conflicts.at(-1);
    const nations=new Set(data.nations.flatMap(item=>[item.country,item.map_name])),isolated=new Set();
    const today=new Date().toISOString().slice(0,10),initialDate=params.get('focal')||params.get('through')||(conflict.active_at_source_boundary?today:(conflict.end_date||`${conflict.last_active_year}-12-31`));
    const state={through:initialDate,focal:initialDate,nodes:[],links:[],graph:null,layoutForce:null,collisionForce:null,positions:new Map(),selected:'',type:'all',timer:null,strategy:null};
    const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
    const events=(data.events||[]).filter(event=>event.conflict_id===conflict.id).sort((a,b)=>a.date_start.localeCompare(b.date_start));
    const years=(data.conflict_years||[]).filter(row=>row.conflict_id===conflict.id);
    document.querySelector('#navigator-title').textContent=`3D · ${conflict.title}`;
    const registerDates=()=>events.length?[...new Set(events.map(event=>event.date_start))]:[...new Set(years.map(row=>`${row.year}-01-01`))].sort();
    function build(){
      const nodes=new Map(),links=new Map(),add=(id,label,kind,metadata={})=>{if(!nodes.has(id))nodes.set(id,{id,label,kind,metadata});return nodes.get(id);},edge=(source,target,relation)=>{if(nodes.has(source)&&nodes.has(target))links.set(`${source}|${target}|${relation}`,{source,target,relation});};
      const center=`conflict:${conflict.id}`,sideA='side:a',sideB='side:b';add(center,conflict.title,'conflict');add(sideA,'Side A','side',{side:'A'});add(sideB,'Side B','side',{side:'B'});edge(center,sideA,'belligerent side');edge(center,sideB,'belligerent side');
      const location=name=>{name=model.display(name||'Unspecified location');const id=`location:${name}`;add(id,name,'location',{location:name});edge(center,id,'conflict location');return id;};
      const nation=(name,side,place,regime='')=>{if(!name)return;name=model.display(name);const id=`nation:${name}`,item=add(id,name,'nation',{country:name,sides:new Set(),regimes:new Set(),citizensIncluded:true});item.metadata.sides.add(side);if(regime)item.metadata.regimes.add(regime);edge(side==='A'?sideA:sideB,id,'state participant');if(place){location(place);edge(id,`location:${model.display(place)}`,'recorded at');}return id;};
      const actor=(name,side)=>{if(!name)return;const country=model.regimeCountry(name,nations);if(country&&!isolated.has(country)){nation(country,side,'',name);return;}const id=`${country?'regime':'actor'}:${name}`;add(id,name,'actor',{side,regimeOf:country});edge(side==='A'?sideA:sideB,id,country?'governing regime':'participant');if(country){const n=nation(country,side,'',name);edge(n,id,'regime of');}};
      conflict.parties_a.flatMap(model.split).forEach(name=>actor(name,'A'));conflict.parties_b.flatMap(model.split).forEach(name=>actor(name,'B'));(conflict.network_locations||conflict.plot_locations||[]).forEach(location);
      years.filter(row=>`${row.year}-01-01`<=state.through).forEach((row,index)=>{model.split(row.side_a).forEach(name=>actor(name,'A'));model.split(row.side_b).forEach(name=>actor(name,'B'));const places=(row.plot_locations||row.locations||[]).map(model.display);places.forEach(place=>{location(place);(row.side_a_states||[]).forEach(name=>nation(name,'A',place));(row.side_b_states||[]).forEach(name=>nation(name,'B',place));});const id=`observation:year-${row.year}-${index}`;add(id,String(row.year),'observation',{row});places.forEach(place=>edge(`location:${place}`,id,'annual observation'));});
      events.filter(event=>event.date_start<=state.through).forEach(event=>{const place=model.display(event.network_location||event.country||event.place||'Unspecified location'),loc=location(place);(event.side_a_states||[]).forEach(name=>nation(name,'A',place));(event.side_b_states||[]).forEach(name=>nation(name,'B',place));model.split(event.side_a).forEach(name=>actor(name,'A'));model.split(event.side_b).forEach(name=>actor(name,'B'));const id=`observation:${event.id}`;add(id,`${event.date_start} · ${event.place||event.country||'event'}`,'observation',{event,posture:model.eventPosture(event)});edge(loc,id,'candidate event');});
      nodes.forEach(node=>{if(node.metadata.sides instanceof Set)node.metadata.sides=[...node.metadata.sides];if(node.metadata.regimes instanceof Set)node.metadata.regimes=[...node.metadata.regimes];});state.nodes=[...nodes.values()];state.links=[...links.values()];state.strategy=model.strategicModel({nodes:state.nodes,edges:state.links.map(link=>({from:typeof link.source==='object'?link.source.id:link.source,to:typeof link.target==='object'?link.target.id:link.target,relation:link.relation}))});
    }
    const baseColor={conflict:'#f07800',side:'#657078',nation:'#7e914b',actor:'#657445',location:'#b56d4d',observation:'#d8c58f'},size={conflict:11,side:9,nation:7,actor:5,location:6,observation:2.2};
    const color=node=>node.metadata.posture?model.postureColor(node.metadata.posture):baseColor[node.kind]||'#8a8a72';
    function show(item){state.selected=item?.id||'';document.querySelector('#navigator-kind').textContent=item?item.kind:'Network extent';document.querySelector('#navigator-selected').textContent=item?item.label:conflict.title;let html='';if(!item)html=`<p>${state.nodes.length} nodes · focal date ${esc(state.focal)}.</p><p>Structural zero-sum proxy: ${((state.strategy?.zeroSumProxy||0)*100).toFixed(1)}%. Potential equilibrium bridges: ${esc(state.strategy?.equilibrium?.map(node=>node.label).join('; ')||'none in this view')}.</p><small>Nation nodes include government and citizens until evidence or “Isolate regime” separates the government. Observation color is a spatial posture inference, not a legal judgment. The proxy describes network exclusivity, not utility, intent, or a legal conclusion.</small>`;else if(item.kind==='observation'&&item.metadata.event){const p=item.metadata.posture,e=item.metadata.event;html=`<p>${esc(e.date_start)} · ${esc(e.place||e.country)}</p><p>${esc(p.role)} posture · ${Math.round(p.certainty*100)}% model certainty</p><small>${esc(p.reasons.join('. '))}.</small>`;}else if(item.kind==='nation'){html=`<p>Sides ${esc(item.metadata.sides.join(' + ')||'not coded')} · citizens included.</p>${item.metadata.regimes.length?`<small>${esc(item.metadata.regimes.join('; '))}</small><button id="navigator-isolate" type="button">${isolated.has(item.metadata.country)?'Recombine regime':'Isolate regime'}</button>`:''}`;}else html=`<p>${esc(item.kind)} in the selected conflict through ${esc(state.through)}.</p>`;document.querySelector('#navigator-inspector-content').innerHTML=html;document.querySelector('#navigator-isolate')?.addEventListener('click',()=>{const c=item.metadata.country;isolated.has(c)?isolated.delete(c):isolated.add(c);render();});}
    function layoutPositions(nodes){const positions=new Map();positions.set(`conflict:${conflict.id}`,{x:0,y:-180,z:0});positions.set('side:a',{x:-270,y:-100,z:0});positions.set('side:b',{x:270,y:-100,z:0});const actors=nodes.filter(node=>['nation','actor'].includes(node.kind));actors.forEach((node,index)=>{const side=node.metadata.side||node.metadata.sides?.[0],same=actors.filter(item=>(item.metadata.side||item.metadata.sides?.[0])===side),order=same.indexOf(node);positions.set(node.id,{x:side==='A'?-310:side==='B'?310:0,y:-20+order*58,z:0});});const locations=nodes.filter(node=>node.kind==='location').sort((a,b)=>a.label.localeCompare(b.label));locations.forEach((node,index)=>{const column=index%3,row=Math.floor(index/3);positions.set(node.id,{x:(column-1)*112,y:35+row*116,z:column%2?0:18});});const eventNodes=nodes.filter(node=>node.metadata.event).sort((a,b)=>a.metadata.event.date_start.localeCompare(b.metadata.event.date_start)||a.id.localeCompare(b.id)),origin=eventNodes[0]?.metadata.event.date_start||state.through,slots=new Map();eventNodes.forEach(node=>{const event=node.metadata.event,location=model.display(event.network_location||event.country||event.place||'Unspecified location'),id=`location:${location}`,anchor=positions.get(id)||{x:0,y:40,z:0},key=`${id}|${event.date_start}`,slot=slots.get(key)||0;slots.set(key,slot+1);positions.set(node.id,model.weeklyOrbit(event,anchor,origin,slot));});nodes.filter(node=>node.kind==='observation'&&!node.metadata.event).forEach((node,index)=>{const angle=index*2.399963,radius=46+Math.sqrt(index)*12;positions.set(node.id,{x:Math.cos(angle)*radius,y:60+Math.sin(angle)*radius,z:index*5});});nodes.forEach((node,index)=>{if(!positions.has(node.id))positions.set(node.id,{x:(index%2?-1:1)*115,y:index*17,z:0});});return positions;}
    function optimize(){state.positions=layoutPositions(state.nodes);state.nodes.forEach(node=>{const p=state.positions.get(node.id);node.x=p.x;node.y=p.y;node.z=p.z;node.fx=null;node.fy=null;node.fz=null;});state.layoutForce?.targets(state.positions);state.graph?.refresh();setTimeout(()=>{state.graph?.d3ReheatSimulation();state.graph?.zoomToFit(700,110);},250);}
    function pullSideNeighborhood(node,translation){if(node.kind!=='side'||!translation)return;const distance=Math.hypot(translation.x||0,translation.y||0,translation.z||0);if(!distance)return;model.graphDistances(node.id,state.links,4).forEach((depth,id)=>{const neighbor=state.nodes.find(item=>item.id===id),factor=model.dragPullFactor(depth,distance);if(!neighbor||!factor)return;const dx=(translation.x||0)*factor,dy=(translation.y||0)*factor,dz=(translation.z||0)*factor;neighbor.x=(neighbor.x||0)+dx;neighbor.y=(neighbor.y||0)+dy;neighbor.z=(neighbor.z||0)+dz;const target=state.positions.get(id);if(target){target.x+=dx;target.y+=dy;target.z+=dz;}});}
    function updateFocalGraph(){if(!state.graph){render();return;}const previous=new Map(state.graph.graphData().nodes.map(node=>[node.id,node])),selected=state.selected;build();const positions=layoutPositions(state.nodes);state.nodes=state.nodes.map(node=>{const existing=previous.get(node.id);if(existing){const p={x:existing.x,y:existing.y,z:existing.z,fx:null,fy:null,fz:null};Object.assign(existing,node,p);return existing;}const p=positions.get(node.id);return {...node,x:p.x,y:p.y,z:p.z,fx:null,fy:null,fz:null};});state.positions=new Map(state.nodes.map(node=>[node.id,{x:node.x,y:node.y,z:node.z}]));state.layoutForce?.targets(state.positions);state.graph.graphData({nodes:state.nodes,links:state.links}).refresh();state.graph.resumeAnimation();setTimeout(()=>state.graph?.d3ReheatSimulation(),0);document.querySelector('#navigator-status').textContent=`Focal ${state.focal} · ${state.nodes.length} nodes · ${state.links.length} relations`;const selectedNode=state.nodes.find(node=>node.id===selected);show(selectedNode||null);renderRegister();}
    function render(){
      build();state.graph?._destructor?.();root.innerHTML='';
      const graph=ForceGraph3D()(root).backgroundColor('rgba(0,0,0,0)').showNavInfo(false)
        .nodeLabel(item=>`<b>${esc(item.label)}</b><br><small>${item.metadata.posture?`${item.metadata.posture.role} ${Math.round(item.metadata.posture.certainty*100)}%`:item.kind}</small>`)
        .nodeColor(item=>state.type==='all'||state.type===item.kind?color(item):'#151a18').nodeVal(item=>size[item.kind]||4).nodeOpacity(.98).nodeResolution(12)
        .linkColor(item=>item.relation==='candidate event'?'#ad5d50':item.relation==='state participant'?'#a7ad78':'#7d9a9c').linkOpacity(.62).linkWidth(item=>item.relation==='candidate event'?1.5:1)
        .enableNodeDrag(true).enableNavigationControls(true).onNodeClick(show).onBackgroundClick(()=>show(null))
        .onNodeDrag((node,translation)=>pullSideNeighborhood(node,translation))
        .onNodeDragEnd(node=>{node.fx=null;node.fy=null;node.fz=null;state.positions.set(node.id,{x:node.x,y:node.y,z:node.z});state.layoutForce?.targets(state.positions);graph.d3ReheatSimulation();})
        .graphData({nodes:state.nodes,links:state.links});
      state.graph=graph;state.layoutForce=model.anchorForce(state.positions);state.collisionForce=model.collisionForce(model.nodeBuffer,4);graph.d3Force('layout',state.layoutForce);graph.d3Force('collision',state.collisionForce);
      graph.d3Force('charge')?.strength(state.nodes.length>700?-30:-75);graph.d3Force('link')?.distance(link=>link.relation.includes('observation')||link.relation==='candidate event'?28:58);
      graph.cameraPosition({x:0,y:0,z:620},{x:0,y:0,z:0},0);graph.controls().enableDamping=true;graph.controls().dampingFactor=.075;
      document.querySelector('#navigator-status').textContent=`Focal ${state.focal} · ${state.nodes.length} nodes · ${state.links.length} relations`;show(null);renderRegister();optimize();
      setTimeout(()=>{graph.resumeAnimation();graph.d3ReheatSimulation();},0);setTimeout(()=>{if(state.graph!==graph)return;graph.resumeAnimation();graph.renderer().render(graph.scene(),graph.camera());},900);
    }
    function renderRegister(){const dates=registerDates();document.querySelector('#navigator-date').textContent=state.focal;document.querySelector('#navigator-register-list').innerHTML=dates.map(date=>{const rows=events.filter(e=>e.date_start===date),yearRows=rows.length?[]:years.filter(row=>`${row.year}-01-01`===date),places=[...new Set((rows.length?rows:yearRows).flatMap(row=>rows.length?[row.place||row.country]:(row.plot_locations||row.locations||[])).filter(Boolean))],count=rows.length||yearRows.length;return `<button data-date="${date}" aria-current="${date===state.focal}"><time>${date}</time><strong>${count} record${count===1?'':'s'}</strong><span>${esc(places.slice(0,3).join(' · ')||'Conflict-year observation')}</span></button>`;}).join('');}
    function setDate(date){if(!registerDates().includes(date))return;state.focal=date;state.through=date;updateFocalGraph();}
    document.querySelector('#navigator-register-list').addEventListener('click',event=>{const button=event.target.closest('[data-date]');if(button)setDate(button.dataset.date);});
    document.querySelector('#navigator-play').addEventListener('click',event=>{if(event.currentTarget.dataset.playing){clearTimeout(state.timer);delete event.currentTarget.dataset.playing;event.currentTarget.textContent='▶ Play';return;}event.currentTarget.dataset.playing='1';event.currentTarget.textContent='Ⅱ Pause';const dates=registerDates();let i=Math.max(0,dates.indexOf(state.focal));if(i===dates.length-1)i=0;const next=()=>{if(!event.currentTarget.dataset.playing)return;setDate(dates[i++]);if(i>=dates.length){delete event.currentTarget.dataset.playing;event.currentTarget.textContent='▶ Play';return;}state.timer=setTimeout(next,900);};next();});
    document.querySelector('#navigator-latest').addEventListener('click',()=>{const latest=registerDates().at(-1);if(latest)setDate(latest);});document.querySelector('#navigator-fit').addEventListener('click',()=>state.graph?.zoomToFit(600,85));document.querySelector('#navigator-optimize').addEventListener('click',optimize);document.querySelector('#navigator-close').addEventListener('click',()=>window.close());
    document.querySelector('#navigator-search').addEventListener('input',event=>{const q=event.target.value.trim().toLowerCase(),item=q?state.nodes.find(n=>n.label.toLowerCase().includes(q)):null;if(item){show(item);const distance=100,m=Math.hypot(item.x||0,item.y||0,item.z||0),ratio=m?1+distance/m:1;state.graph.cameraPosition(m?{x:item.x*ratio,y:item.y*ratio,z:item.z*ratio}:{z:distance},item,700);}});
    document.querySelector('#navigator-type').addEventListener('change',event=>{state.type=event.target.value;state.graph.nodeColor(item=>state.type==='all'||state.type===item.kind?color(item):'#151a18').refresh();});document.querySelector('#navigator-clear').addEventListener('click',()=>{state.type='all';document.querySelector('#navigator-type').value='all';document.querySelector('#navigator-search').value='';state.graph.nodeColor(color).refresh();show(null);});render();
  };
  window.addEventListener('load',start,{once:true});
})();
